[package]
name = "grpc-hello-server"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
prost = "0.13.1"
tokio = { version = "1.39.3", features = ["rt-multi-thread"] }
tonic = "0.12.2"

[build-dependencies]
tonic-build = "0.12.2"
